### ISSUE TITLE
condition on migration option produces inf values

### ISSUE THREAD

**Issue by stsmall** [kern-lab/FILET#1]
Hi @andrewkern,
I was working with msmove to create training simulations. When I use the '-c' option in twoPopnStats_forML to condition on migration (//asterisk in msmove) the values of dd1 and dd2 are inf or very large.

Below are examples from the trainingSims directory:
twoPopnStats_forML -c 20 14 < mig21.msOut
dd1 = inf
dd2 = 4775280.894101

twoPopnStats_forML 20 14 < mig21.msOut
dd1 = 0.817502
dd2 = 1.247589

thanks,
@stsmall

**Comment by andrewkern** [comment]
Hi @stsmall-- this is poorly documented code. my apologies. The "-c" flag should go after the two sample sizes such that your call would be

`twoPopnStats_forML 20 14 -c < mig21.msOut`

let me know if that works for you

**Comment by stsmall** [comment]
Hi @andrewkern,
That was it. My bad for not trying more combinations of things. My legacy will be a trail of github issues that were easily solved if only I had stopped to think :)
