### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by pengyan19** [kern-lab/FILET#7]
Hi; when i used the "make" code to compile the FILET software, i met a question as follows:

/usr/bin/ld: cannot find -lgsl
/usr/bin/ld: cannot find -lgslcblas
collect2: error: ld returned 1 exit status
make: *** [msMaskAllRows] Error 1

**Comment by andrewkern** [comment]
hi there @pengyan19 -- it seems that you don't have the GSL library installed on your system. Please be sure to see the[ readme](https://github.com/kr-colab/FILET/blob/master/README.md) for install instructions
